# Generated by Django 2.2.4 on 2020-10-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
